---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudautoscale.infra.doodle.com
  resources:
  - awsrdsinstances
  - mongodbatlasclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudautoscale.infra.doodle.com
  resources:
  - awsrdsinstances/finalizers
  - mongodbatlasclusters/finalizers
  verbs:
  - update
- apiGroups:
  - cloudautoscale.infra.doodle.com
  resources:
  - awsrdsinstances/status
  - mongodbatlasclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
