{{- if .Values.clusterRBAC.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cloud-autoscale-controller.fullname" . }}-edit
  labels:
    app.kubernetes.io/name: {{ include "cloud-autoscale-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "cloud-autoscale-controller.chart" . }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
rules:
- apiGroups:
  - "cloudautoscale.infra.doodle.com"
  resources:
  - cloudautoscalerealms
  - cloudautoscaleclients
  - cloudautoscaleusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "cloudautoscale.infra.doodle.com"
  resources:
  - cloudautoscalerealms/status
  - cloudautoscaleclients/status
  - cloudautoscaleusers/status
  verbs:
  - get
{{- end }}
